cat > environment.yml <<'YML'
name: lc_soliton
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - numpy>=1.26,<2.0
  - cupy-cuda12x>=13.0,<14.0a0
  - scipy>=1.11,<2.0
  - numba>=0.59,<0.60
  - matplotlib>=3.8,<4.0
  - pyyaml
  - pip
  - pip:
      - ruff>=0.6,<0.7
      - pytest>=7.4,<8.0
YML
